### ISSUE TITLE
annotations to stacked chart do not show lines

### ISSUE THREAD

**Issue by c-arnab** [TargetProcess/tauCharts#189]
tried adding annotation to stacked chart here(http://jsfiddle.net/eawan9ym/28/) but do not see any lines as in annotation example as here(https://jsfiddle.net/taucharts/2o9kcm7w/)

**Comment by vladminsky** [comment]
@c-arnab 

Yes, this is definitely inconsistency issue which have to be fixed for ordinal scales.

I'm not sure I can explain the root cause in two words, so look at this example:

http://jsfiddle.net/taucharts/nao07eyr/

..note how line is built from point to point and doesn't touch the plot borders.
By analogy.. in the original fiddle - line width just appears to equal zero.

The only workaround for now is to add an artifical ticks on ordinal scale X around the stacked funnel.

I understand it is ugly and will try to fix the issue soon.
