### ISSUE TITLE
Simple way to set X or Y to int values

### ISSUE THREAD

**Issue by icusmiling** [TargetProcess/tauCharts#194]
Hi again,

Trying to find a simple way to set the charts to only have ticks at integer values, with no decimal values in between. Any thoughts? 

Thanks!

**Comment by vladminsky** [comment]
@icusmiling 

There is no particular integer scale, but we can use custom formatter to display integer axis labels only.

http://jsfiddle.net/taucharts/s0mhg26d/

NOTE: decimal ticks stay visible and formatter for tooltip should be explicitly specified (otherwise it will format decimal values as empty string by default).

Are you OK with such workaround?

**Comment by icusmiling** [comment]
That worked perfectly! Thanks!!
