### ISSUE TITLE
typeError

### ISSUE THREAD

**Issue by gabegaster** [TargetProcess/tauCharts#32]
I'm loading from latest on the cdn. I get this error.

```Uncaught TypeError: Cannot read property 'time' of undefined tauCharts.min.js:```

**Comment by vladminsky** [comment]
Hi,

Thanks for your interest to tauCharts.

I assume the error is caused by the fact you didn't load d3 before tauCharts so "d3.time" function is undefined in this case.

Looks like you already found how to reference tauCharts from CDN in the documentation:
http://api.taucharts.com/download/README.html

Also we have a plans to make in parallel a full assembly with all dependencies included so users shouldn't think about underscore and d3.

We are just starting and will be be happy to hear about your experience / problems / insights while using tauCharts.

-----------
Vladimir

**Comment by gabegaster** [comment]
I had been including d3, but perhaps you're right that it hadn't been loaded yet for some reason. Anyway, as a suggestion (which I commented on in, under http://api.taucharts.com/download/README.html) it would be good to specify versions (a version of d3 and a specific version of taucharts).

Also if you included versions of underscore and d3 in taucharts, I've seen errors that happen when you include multiple versions / copies of a package. So if a user includes taucharts and underscore, this could create issues for them.
